ci cd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,10 +53,12 @@ jobs:
     - name: Get Terraform Outputs
       id: terraform_outputs
       run: |
-        # Execute o comando do Terraform para obter as saídas desejadas
-        instance_ip=$(terraform output -json | jq -r '.aws_instance_e_ssh.value[0]')
+        instance_ip=$(terraform output -json instance_ip)
+        if [ -z "$instance_ip" ]; then
+          echo "Instance IP not found in Terraform output"
+          exit 1
+        fi
         echo "::set-env name=INSTANCE_IP::$instance_ip"
-      working-directory: terraform
 
     - name: Update Ansible Hosts
       run: |
@@ -67,6 +69,7 @@ jobs:
         fi
         echo "[maquina_wp]" > ansible/hosts
         echo "$instance_ip" >> ansible/hosts
+
 
     - name: Run Ansible Playbook
       run: ansible-playbook -i ansible/hosts ansible/provisionar.yml
