ci cd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,26 +44,36 @@ jobs:
         cd terraform
         terraform apply -auto-approve tfplan
         
-    - name: Obter Saídas do Terraform
+    - name: Get Terraform Outputs
+      id: terraform_outputs
       run: |
         cd terraform
-        terraform output -json > tf_output.json
-        instance_ip=$(jq -r '.aws_instance_ssh.value[0]' tf_output.json)
+        terraform init -input=false
+        terraform apply -auto-approve -input=false
+        instance_ip=$(terraform output -raw instance_ip)
         if [ -z "$instance_ip" ]; then
-          echo "IP da instância não encontrado na saída do Terraform"
+          echo "Instance IP not found in Terraform output"
           exit 1
         fi
         echo "::set-env name=INSTANCE_IP::$instance_ip"
 
-    - name: Atualizar Arquivo de Hosts do Ansible
+    - name: Update Ansible Hosts
       run: |
         instance_ip="${{ env.INSTANCE_IP }}"
         if [ -z "$instance_ip" ]; then
-          echo "IP da instância não encontrado na saída do Terraform"
+          echo "Instance IP not found in Terraform output"
           exit 1
         fi
-        echo "[maquina_wp]" >> ansible/hosts
+        echo "[maquina_wp]" > ansible/hosts
         echo "$instance_ip" >> ansible/hosts
+          run: |
+            instance_ip="${{ env.INSTANCE_IP }}"
+            if [ -z "$instance_ip" ]; then
+              echo "IP da instância não encontrado na saída do Terraform"
+              exit 1
+            fi
+            echo "[maquina_wp]" >> ansible/hosts
+            echo "$instance_ip" >> ansible/hosts
 
     - name: Executar Playbook do Ansible
       run: ansible-playbook -i ansible/hosts ansible/provisionar.yml
